use_logit: False
alpha: False

height: 96
width: 64
scale: "dB"

L: 3
K: 40
n_filters: 512
learntop: True

n_epochs: 20
optimizer: "adamax"
batch_size: 32
learning_rate: 0.001

sigma1: 1.
sigmaL: 0.01
num_classes: 10
progression: 'logarithmic'