use_logit: False
alpha: False

version: "v2"
ema: False

height: 96
width: 64
scale: "dB"

n_filters: 128
sigma1: 30.
sigmaL: 0.01
num_classes: 200
progression: 'geometric'

T: 8
step_lr: 0.000006

n_epochs: 500
optimizer: "adam"
batch_size: 32
learning_rate: 0.00006